# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: accounts.proto for package 'v1'

require "grpc"
require "accounts_pb"

module V1
  module Accounts
    # Accounts are users, services or tokens who connect to and act within the strongDM network.
    class Service
      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "v1.Accounts"

      # Create registers a new Account.
      rpc :Create, AccountCreateRequest, AccountCreateResponse
      # Get reads one Account by ID.
      rpc :Get, AccountGetRequest, AccountGetResponse
      # Update patches a Account by ID.
      rpc :Update, AccountUpdateRequest, AccountUpdateResponse
      # Delete removes a Account by ID.
      rpc :Delete, AccountDeleteRequest, AccountDeleteResponse
      # List gets a list of Accounts matching a given set of criteria.
      rpc :List, AccountListRequest, AccountListResponse
    end

    Stub = Service.rpc_stub_class
  end
end
