# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drivers.proto

require "google/protobuf"

require "options_pb"
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("drivers.proto", :syntax => :proto3) do
    add_message "v1.Driver" do
      oneof :driver do
        optional :mysql, :message, 1, "v1.Mysql"
      end
    end
    add_message "v1.Mysql" do
      optional :username, :string, 1
      optional :password, :string, 2
      optional :database, :string, 3
      optional :port, :string, 4
    end
  end
end

module V1
  Driver = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.Driver").msgclass
  Mysql = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.Mysql").msgclass
end
