# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drivers.proto

require "google/protobuf"

require "protoc-gen-swagger/options/annotations_pb"
require "options_pb"
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("drivers.proto", :syntax => :proto3) do
    add_message "v1.Driver" do
      oneof :driver do
        optional :http_basic_auth, :message, 448320780, "v1.HTTPBasicAuth"
        optional :http_no_auth, :message, 435770653, "v1.HTTPNoAuth"
        optional :http_auth, :message, 224436590, "v1.HTTPAuth"
        optional :mysql, :message, 386203715, "v1.Mysql"
        optional :aurora_mysql, :message, 18289005, "v1.AuroraMysql"
        optional :clustrix, :message, 532386964, "v1.Clustrix"
        optional :maria, :message, 466202260, "v1.Maria"
        optional :memsql, :message, 269999277, "v1.Memsql"
        optional :athena, :message, 86524680, "v1.Athena"
      end
    end
    add_message "v1.HTTPBasicAuth" do
      optional :url, :string, 1
      optional :healthcheck_path, :string, 2
      optional :username, :string, 3
      optional :password, :string, 4
      optional :headers_blacklist, :string, 5
      optional :default_path, :string, 6
      optional :subdomain, :string, 7
    end
    add_message "v1.HTTPNoAuth" do
      optional :url, :string, 1
      optional :healthcheck_path, :string, 2
      optional :headers_blacklist, :string, 3
      optional :default_path, :string, 4
      optional :subdomain, :string, 5
    end
    add_message "v1.HTTPAuth" do
      optional :url, :string, 1
      optional :healthcheck_path, :string, 2
      optional :auth_header, :string, 3
      optional :headers_blacklist, :string, 4
      optional :default_path, :string, 5
      optional :subdomain, :string, 6
    end
    add_message "v1.Mysql" do
      optional :hostname, :string, 1
      optional :username, :string, 2
      optional :password, :string, 3
      optional :database, :string, 4
      optional :port, :int32, 5
    end
    add_message "v1.AuroraMysql" do
      optional :hostname, :string, 1
      optional :username, :string, 2
      optional :password, :string, 3
      optional :database, :string, 4
      optional :port, :int32, 5
    end
    add_message "v1.Clustrix" do
      optional :hostname, :string, 1
      optional :username, :string, 2
      optional :password, :string, 3
      optional :database, :string, 4
      optional :port, :int32, 5
    end
    add_message "v1.Maria" do
      optional :hostname, :string, 1
      optional :username, :string, 2
      optional :password, :string, 3
      optional :database, :string, 4
      optional :port, :int32, 5
    end
    add_message "v1.Memsql" do
      optional :hostname, :string, 1
      optional :username, :string, 2
      optional :password, :string, 3
      optional :database, :string, 4
      optional :port, :int32, 5
    end
    add_message "v1.Athena" do
      optional :access_key, :string, 1
      optional :secretAccessKey, :string, 2
      optional :region, :string, 3
      optional :output, :string, 4
    end
  end
end

module V1
  Driver = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.Driver").msgclass
  HTTPBasicAuth = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.HTTPBasicAuth").msgclass
  HTTPNoAuth = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.HTTPNoAuth").msgclass
  HTTPAuth = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.HTTPAuth").msgclass
  Mysql = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.Mysql").msgclass
  AuroraMysql = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AuroraMysql").msgclass
  Clustrix = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.Clustrix").msgclass
  Maria = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.Maria").msgclass
  Memsql = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.Memsql").msgclass
  Athena = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.Athena").msgclass
end
