# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: nodes.proto for package 'v1'

require 'grpc'
require 'nodes_pb'

module V1
  module Nodes
    # Nodes are proxies in strongDM responsible to communicate with servers
    # (relays) and clients (gateways).
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'v1.Nodes'

      # Create registers a new node.
      rpc :Create, NodeCreateRequest, NodeCreateResponse
      # Get reads one node by ID.
      rpc :Get, NodeGetRequest, NodeGetResponse
      # Update patches a node by ID.
      rpc :Update, NodeUpdateRequest, NodeUpdateResponse
      # Delete removes a node by ID.
      rpc :Delete, NodeDeleteRequest, NodeDeleteResponse
      # List is a batched Get call.
      rpc :List, NodeListRequest, NodeListResponse
      # BatchUpdate is a batched Update call.
      rpc :BatchUpdate, NodeBatchUpdateRequest, NodeBatchUpdateResponse
      # BatchDelete is a batched Delete call.
      rpc :BatchDelete, NodeBatchDeleteRequest, NodeBatchDeleteResponse
    end

    Stub = Service.rpc_stub_class
  end
end
