# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: nodes.proto for package 'v1'

require "grpc"
require "nodes_pb"

module V1
  module Nodes
    # Nodes are proxies in the strongDM network. They come in two flavors: relays,
    # which communicate with resources, and gateways, which communicate with
    # clients.
    class Service
      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "v1.Nodes"

      # Create registers a new Node.
      rpc :Create, NodeCreateRequest, NodeCreateResponse
      # Get reads one Node by ID.
      rpc :Get, NodeGetRequest, NodeGetResponse
      # Update patches a Node by ID.
      rpc :Update, NodeUpdateRequest, NodeUpdateResponse
      # Delete removes a Node by ID.
      rpc :Delete, NodeDeleteRequest, NodeDeleteResponse
      # List gets a list of Nodes matching a given set of criteria.
      rpc :List, NodeListRequest, NodeListResponse
    end

    Stub = Service.rpc_stub_class
  end
end
