# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: resources.proto for package 'v1'

require "grpc"
require "resources_pb"

module V1
  module Resources
    class Service
      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "v1.Resources"

      # Create registers a new Resource.
      rpc :Create, ResourceCreateRequest, ResourceCreateResponse
      # Get reads one Resource by ID.
      rpc :Get, ResourceGetRequest, ResourceGetResponse
      # Update patches a Resource by ID.
      rpc :Update, ResourceUpdateRequest, ResourceUpdateResponse
      # Delete removes a Resource by ID.
      rpc :Delete, ResourceDeleteRequest, ResourceDeleteResponse
      # List gets a list of Resources matching a given set of criteria.
      rpc :List, ResourceListRequest, ResourceListResponse
    end

    Stub = Service.rpc_stub_class
  end
end
