# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: roles.proto for package 'v1'

require 'grpc'
require 'roles_pb'

module V1
  module Roles
    # Roles are
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'v1.Roles'

      # Create registers a new role.
      rpc :Create, RoleCreateRequest, RoleCreateResponse
      # Get reads one role by ID.
      rpc :Get, RoleGetRequest, RoleGetResponse
      # Update patches a Role by ID.
      rpc :Update, RoleUpdateRequest, RoleUpdateResponse
      # Delete removes a Role by ID.
      rpc :Delete, RoleDeleteRequest, RoleDeleteResponse
      # List is a batched Get call.
      rpc :List, RoleListRequest, RoleListResponse
    end

    Stub = Service.rpc_stub_class
  end
end
