# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec.proto

require 'google/protobuf'

require 'protoc-gen-swagger/options/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("spec.proto", :syntax => :proto3) do
    add_message "v1.ErrorDetail" do
      optional :message, :string, 1
    end
    add_message "v1.CreateRequestMetadata" do
    end
    add_message "v1.CreateResponseMetadata" do
      optional :affected, :int64, 1
    end
    add_message "v1.GetRequestMetadata" do
    end
    add_message "v1.GetResponseMetadata" do
      optional :found, :int64, 1
    end
    add_message "v1.UpdateRequestMetadata" do
    end
    add_message "v1.UpdateResponseMetadata" do
      optional :affected, :int64, 1
    end
    add_message "v1.DeleteRequestMetadata" do
    end
    add_message "v1.DeleteResponseMetadata" do
      optional :affected, :int64, 1
    end
    add_message "v1.BatchUpdateRequestMetadata" do
    end
    add_message "v1.BatchUpdateResponseMetadata" do
      optional :found, :int64, 1
      optional :affected, :int64, 2
    end
    add_message "v1.BatchDeleteRequestMetadata" do
    end
    add_message "v1.BatchDeleteResponseMetadata" do
      optional :found, :int64, 1
      optional :affected, :int64, 2
    end
    add_message "v1.ListRequestMetadata" do
      optional :page, :string, 1
    end
    add_message "v1.ListResponseMetadata" do
      optional :next_page, :string, 1
      optional :found, :int64, 2
    end
  end
end

module V1
  ErrorDetail = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ErrorDetail").msgclass
  CreateRequestMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.CreateRequestMetadata").msgclass
  CreateResponseMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.CreateResponseMetadata").msgclass
  GetRequestMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.GetRequestMetadata").msgclass
  GetResponseMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.GetResponseMetadata").msgclass
  UpdateRequestMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.UpdateRequestMetadata").msgclass
  UpdateResponseMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.UpdateResponseMetadata").msgclass
  DeleteRequestMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.DeleteRequestMetadata").msgclass
  DeleteResponseMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.DeleteResponseMetadata").msgclass
  BatchUpdateRequestMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.BatchUpdateRequestMetadata").msgclass
  BatchUpdateResponseMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.BatchUpdateResponseMetadata").msgclass
  BatchDeleteRequestMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.BatchDeleteRequestMetadata").msgclass
  BatchDeleteResponseMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.BatchDeleteResponseMetadata").msgclass
  ListRequestMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ListRequestMetadata").msgclass
  ListResponseMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ListResponseMetadata").msgclass
end
