# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spec.proto

require 'google/protobuf'

require 'options_pb'
require 'protoc-gen-swagger/options/annotations_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("spec.proto", :syntax => :proto3) do
    add_message "v1.AlreadyExistsError" do
      repeated :entities, :string, 1
    end
    add_message "v1.NotFoundError" do
      repeated :entities, :string, 1
    end
    add_message "v1.BadRequestError" do
    end
    add_message "v1.AuthenticationError" do
    end
    add_message "v1.PermissionError" do
    end
    add_message "v1.InternalError" do
    end
    add_message "v1.RateLimitError" do
    end
    add_message "v1.CreateRequestMetadata" do
    end
    add_message "v1.CreateResponseMetadata" do
    end
    add_message "v1.GetRequestMetadata" do
    end
    add_message "v1.GetResponseMetadata" do
    end
    add_message "v1.UpdateRequestMetadata" do
    end
    add_message "v1.UpdateResponseMetadata" do
    end
    add_message "v1.DeleteRequestMetadata" do
    end
    add_message "v1.DeleteResponseMetadata" do
    end
    add_message "v1.ListRequestMetadata" do
      optional :cursor, :string, 1
      optional :page, :int32, 2
      optional :limit, :int32, 3
    end
    add_message "v1.ListResponseMetadata" do
      optional :next_cursor, :string, 1
      optional :found, :int32, 2
    end
  end
end

module V1
  AlreadyExistsError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AlreadyExistsError").msgclass
  NotFoundError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.NotFoundError").msgclass
  BadRequestError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.BadRequestError").msgclass
  AuthenticationError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AuthenticationError").msgclass
  PermissionError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PermissionError").msgclass
  InternalError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.InternalError").msgclass
  RateLimitError = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.RateLimitError").msgclass
  CreateRequestMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.CreateRequestMetadata").msgclass
  CreateResponseMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.CreateResponseMetadata").msgclass
  GetRequestMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.GetRequestMetadata").msgclass
  GetResponseMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.GetResponseMetadata").msgclass
  UpdateRequestMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.UpdateRequestMetadata").msgclass
  UpdateResponseMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.UpdateResponseMetadata").msgclass
  DeleteRequestMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.DeleteRequestMetadata").msgclass
  DeleteResponseMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.DeleteResponseMetadata").msgclass
  ListRequestMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ListRequestMetadata").msgclass
  ListResponseMetadata = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ListResponseMetadata").msgclass
end
