# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_grants.proto

require "google/protobuf"

require "google/api/annotations_pb"
require "protoc-gen-swagger/options/annotations_pb"
require "options_pb"
require "spec_pb"
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user_grants.proto", :syntax => :proto3) do
    add_message "v1.UserGrantCreateRequest" do
      optional :meta, :message, 1, "v1.CreateRequestMetadata"
      optional :user_grant, :message, 2, "v1.UserGrant"
    end
    add_message "v1.UserGrantCreateResponse" do
      optional :meta, :message, 1, "v1.CreateResponseMetadata"
      optional :user_grant, :message, 2, "v1.UserGrant"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.UserGrantGetRequest" do
      optional :meta, :message, 1, "v1.GetRequestMetadata"
      optional :id, :string, 2
    end
    add_message "v1.UserGrantGetResponse" do
      optional :meta, :message, 1, "v1.GetResponseMetadata"
      optional :user_grant, :message, 2, "v1.UserGrant"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.UserGrantDeleteRequest" do
      optional :meta, :message, 1, "v1.DeleteRequestMetadata"
      optional :id, :string, 2
    end
    add_message "v1.UserGrantDeleteResponse" do
      optional :meta, :message, 1, "v1.DeleteResponseMetadata"
      optional :rate_limit, :message, 2, "v1.RateLimitMetadata"
    end
    add_message "v1.UserGrantListRequest" do
      optional :meta, :message, 1, "v1.ListRequestMetadata"
      optional :filter, :string, 2
    end
    add_message "v1.UserGrantListResponse" do
      optional :meta, :message, 1, "v1.ListResponseMetadata"
      repeated :user_grants, :message, 2, "v1.UserGrant"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.UserGrant" do
      optional :id, :string, 1
      optional :resource_id, :string, 2
      optional :user_id, :string, 3
    end
  end
end

module V1
  UserGrantCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.UserGrantCreateRequest").msgclass
  UserGrantCreateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.UserGrantCreateResponse").msgclass
  UserGrantGetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.UserGrantGetRequest").msgclass
  UserGrantGetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.UserGrantGetResponse").msgclass
  UserGrantDeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.UserGrantDeleteRequest").msgclass
  UserGrantDeleteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.UserGrantDeleteResponse").msgclass
  UserGrantListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.UserGrantListRequest").msgclass
  UserGrantListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.UserGrantListResponse").msgclass
  UserGrant = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.UserGrant").msgclass
end
