# @internal This file was generated by constgen. DO NOT EDIT.

module SDM

	# Permission Levels, shared by all entities capable of making authenticated requests against StrongDM.
	module PermissionLevel
		ROOT_ADMIN = "root-admin"
		ADMIN = "admin"
		DATABASE_ADMIN = "database-admin"
		TEAM_LEADER = "multi-team-leader"
		USER = "user"
		RELAY = "relay"
		ADMIN_TOKEN = "admin-token"
		SCIM_TOKEN = "scim-token"
		SERVICE = "service"
		SUSPENDED = "suspended"
		EMPTY = ""
	end

	# Node Lifecycle States, defining whether a node was last reported online, offline, restarting, etc.
	module NodeState
		NEW = "new"
		VERIFYING_RESTART = "verifying_restart"
		AWAITING_RESTART = "awaiting_restart"
		RESTARTING = "restarting"
		STARTED = "started"
		STOPPED = "stopped"
		DEAD = "dead"
	end

	# Providers responsible for managing roles and users.
	# None, or an empty string, implies the user is managed by strongDM.
	module Provider
		NONE = ""
		OKTA = "okta"
		SAIL_POINT = "sailpoint"
		AZURE = "azure"
		GENERIC = "generic"
		ONE_LOGIN = "onelogin"
		GOOGLE = "google"
	end
end