# Copyright 2020 StrongDM Inc
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account_attachments.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'protoc-gen-swagger/options/annotations_pb'
require 'options_pb'
require 'spec_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("account_attachments.proto", :syntax => :proto3) do
    add_message "v1.AccountAttachmentCreateRequest" do
      optional :meta, :message, 1, "v1.CreateRequestMetadata"
      optional :account_attachment, :message, 2, "v1.AccountAttachment"
    end
    add_message "v1.AccountAttachmentCreateResponse" do
      optional :meta, :message, 1, "v1.CreateResponseMetadata"
      optional :account_attachment, :message, 2, "v1.AccountAttachment"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.AccountAttachmentGetRequest" do
      optional :meta, :message, 1, "v1.GetRequestMetadata"
      optional :id, :string, 2
    end
    add_message "v1.AccountAttachmentGetResponse" do
      optional :meta, :message, 1, "v1.GetResponseMetadata"
      optional :account_attachment, :message, 2, "v1.AccountAttachment"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.AccountAttachmentDeleteRequest" do
      optional :meta, :message, 1, "v1.DeleteRequestMetadata"
      optional :id, :string, 2
    end
    add_message "v1.AccountAttachmentDeleteResponse" do
      optional :meta, :message, 1, "v1.DeleteResponseMetadata"
      optional :rate_limit, :message, 2, "v1.RateLimitMetadata"
    end
    add_message "v1.AccountAttachmentListRequest" do
      optional :meta, :message, 1, "v1.ListRequestMetadata"
      optional :filter, :string, 2
    end
    add_message "v1.AccountAttachmentListResponse" do
      optional :meta, :message, 1, "v1.ListResponseMetadata"
      repeated :account_attachments, :message, 2, "v1.AccountAttachment"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.AccountAttachment" do
      optional :id, :string, 1
      optional :account_id, :string, 2
      optional :role_id, :string, 3
    end
  end
end

module V1
  AccountAttachmentCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AccountAttachmentCreateRequest").msgclass
  AccountAttachmentCreateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AccountAttachmentCreateResponse").msgclass
  AccountAttachmentGetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AccountAttachmentGetRequest").msgclass
  AccountAttachmentGetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AccountAttachmentGetResponse").msgclass
  AccountAttachmentDeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AccountAttachmentDeleteRequest").msgclass
  AccountAttachmentDeleteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AccountAttachmentDeleteResponse").msgclass
  AccountAttachmentListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AccountAttachmentListRequest").msgclass
  AccountAttachmentListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AccountAttachmentListResponse").msgclass
  AccountAttachment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AccountAttachment").msgclass
end
