# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: accounts_groups.proto

require "google/protobuf"

require "options_pb"
require "spec_pb"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("accounts_groups.proto", :syntax => :proto3) do
    add_message "v1.AccountGroupCreateRequest" do
      optional :meta, :message, 1, "v1.CreateRequestMetadata"
      optional :account_group, :message, 2, "v1.AccountGroup"
    end
    add_message "v1.AccountGroupCreateResponse" do
      optional :meta, :message, 1, "v1.CreateResponseMetadata"
      optional :account_group, :message, 2, "v1.AccountGroup"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.AccountGroupGetRequest" do
      optional :meta, :message, 1, "v1.GetRequestMetadata"
      optional :id, :string, 2
    end
    add_message "v1.AccountGroupGetResponse" do
      optional :meta, :message, 1, "v1.GetResponseMetadata"
      optional :account_group, :message, 2, "v1.AccountGroup"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.AccountGroupDeleteRequest" do
      optional :meta, :message, 1, "v1.DeleteRequestMetadata"
      optional :id, :string, 2
    end
    add_message "v1.AccountGroupDeleteResponse" do
      optional :meta, :message, 1, "v1.DeleteResponseMetadata"
      optional :rate_limit, :message, 2, "v1.RateLimitMetadata"
    end
    add_message "v1.AccountGroupListRequest" do
      optional :meta, :message, 1, "v1.ListRequestMetadata"
      optional :filter, :string, 2
    end
    add_message "v1.AccountGroupListResponse" do
      optional :meta, :message, 1, "v1.ListResponseMetadata"
      repeated :account_groups, :message, 2, "v1.AccountGroup"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.AccountGroup" do
      optional :id, :string, 1
      optional :account_id, :string, 2
      optional :group_id, :string, 3
    end
  end
end

module V1
  AccountGroupCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AccountGroupCreateRequest").msgclass
  AccountGroupCreateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AccountGroupCreateResponse").msgclass
  AccountGroupGetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AccountGroupGetRequest").msgclass
  AccountGroupGetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AccountGroupGetResponse").msgclass
  AccountGroupDeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AccountGroupDeleteRequest").msgclass
  AccountGroupDeleteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AccountGroupDeleteResponse").msgclass
  AccountGroupListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AccountGroupListRequest").msgclass
  AccountGroupListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AccountGroupListResponse").msgclass
  AccountGroup = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AccountGroup").msgclass
end
