# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: activities.proto

require "google/protobuf"

require "google/protobuf/timestamp_pb"
require "options_pb"
require "spec_pb"
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("activities.proto", :syntax => :proto3) do
    add_message "v1.ActivityGetRequest" do
      optional :meta, :message, 1, "v1.GetRequestMetadata"
      optional :id, :string, 2
    end
    add_message "v1.ActivityGetResponse" do
      optional :meta, :message, 1, "v1.GetResponseMetadata"
      optional :activity, :message, 2, "v1.Activity"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.ActivityListRequest" do
      optional :meta, :message, 1, "v1.ListRequestMetadata"
      optional :filter, :string, 2
    end
    add_message "v1.ActivityListResponse" do
      optional :meta, :message, 1, "v1.ListResponseMetadata"
      repeated :activities, :message, 2, "v1.Activity"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.Activity" do
      optional :id, :string, 1
      optional :verb, :string, 2
      optional :description, :string, 3
      optional :completed_at, :message, 4, "google.protobuf.Timestamp"
      repeated :entities, :message, 5, "v1.ActivityEntity"
      optional :ip_address, :string, 6
      optional :actor, :message, 7, "v1.ActivityActor"
      optional :user_agent, :string, 8
    end
    add_message "v1.ActivityEntity" do
      optional :id, :string, 1
      optional :type, :string, 2
      optional :name, :string, 3
      optional :email, :string, 4
      optional :external_id, :string, 5
    end
    add_message "v1.ActivityActor" do
      optional :id, :string, 1
      optional :email, :string, 2
      optional :first_name, :string, 3
      optional :last_name, :string, 4
      optional :activity_external_id, :string, 5
    end
  end
end

module V1
  ActivityGetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ActivityGetRequest").msgclass
  ActivityGetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ActivityGetResponse").msgclass
  ActivityListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ActivityListRequest").msgclass
  ActivityListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ActivityListResponse").msgclass
  Activity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.Activity").msgclass
  ActivityEntity = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ActivityEntity").msgclass
  ActivityActor = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ActivityActor").msgclass
end
