# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: activities.proto for package 'v1'

require "grpc"
require "activities_pb"

module V1
  module Activities
    # An Activity is a record of an action taken against a strongDM deployment, e.g.
    # a user creation, resource deletion, sso configuration change, etc. The Activities
    # service is read-only.
    class Service
      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "v1.Activities"

      # Get reads one Activity by ID.
      rpc :Get, V1::ActivityGetRequest, V1::ActivityGetResponse
      # List gets a list of Activities matching a given set of criteria.
      rpc :List, V1::ActivityListRequest, V1::ActivityListResponse
    end

    Stub = Service.rpc_stub_class
  end
end
