# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: audits.proto

require "google/protobuf"

require "options_pb"
require "spec_pb"
require "access_rules_pb"
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("audits.proto", :syntax => :proto3) do
    add_message "v1.GetAccessRulesRequest" do
      optional :meta, :message, 1, "v1.GetRequestMetadata"
      optional :when, :string, 2
    end
    add_message "v1.GetAccessRulesResponse" do
      optional :meta, :message, 1, "v1.GetResponseMetadata"
      repeated :access_rules, :message, 2, "v1.AccessRule"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
  end
end

module V1
  GetAccessRulesRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.GetAccessRulesRequest").msgclass
  GetAccessRulesResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.GetAccessRulesResponse").msgclass
end
