# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authorization_policies.proto

require "google/protobuf"

require "options_pb"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("authorization_policies.proto", :syntax => :proto3) do
    add_message "v1.AuthorizationPolicy" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :description, :string, 3
      repeated :items, :message, 4, "v1.AuthorizationPolicyItem"
    end
    add_message "v1.AuthorizationPolicyItem" do
      oneof :item do
        optional :principal_all, :message, 1, "v1.AuthorizationPolicyItemPrincipalAll"
        optional :principal_by_ids, :message, 2, "v1.AuthorizationPolicyItemPrincipalByIds"
        optional :resources_all, :message, 3, "v1.AuthorizationPolicyItemResourcesAll"
        optional :resource_by_ids, :message, 4, "v1.AuthorizationPolicyItemResourceByIds"
      end
    end
    add_message "v1.AuthorizationPolicyItemPrincipalAll" do
    end
    add_message "v1.AuthorizationPolicyItemPrincipalByIds" do
      repeated :ids, :string, 1
    end
    add_message "v1.AuthorizationPolicyItemResourcesAll" do
    end
    add_message "v1.AuthorizationPolicyItemResourceByIds" do
      repeated :ids, :string, 1
    end
  end
end

module V1
  AuthorizationPolicy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AuthorizationPolicy").msgclass
  AuthorizationPolicyItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AuthorizationPolicyItem").msgclass
  AuthorizationPolicyItemPrincipalAll = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AuthorizationPolicyItemPrincipalAll").msgclass
  AuthorizationPolicyItemPrincipalByIds = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AuthorizationPolicyItemPrincipalByIds").msgclass
  AuthorizationPolicyItemResourcesAll = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AuthorizationPolicyItemResourcesAll").msgclass
  AuthorizationPolicyItemResourceByIds = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AuthorizationPolicyItemResourceByIds").msgclass
end
