# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control_panel.proto

require "google/protobuf"

require "options_pb"
require "spec_pb"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("control_panel.proto", :syntax => :proto3) do
    add_message "v1.ControlPanelGetSSHCAPublicKeyRequest" do
      optional :meta, :message, 1, "v1.GetRequestMetadata"
    end
    add_message "v1.ControlPanelGetSSHCAPublicKeyResponse" do
      optional :meta, :message, 1, "v1.GetResponseMetadata"
      optional :public_key, :string, 2
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.ControlPanelGetRDPCAPublicKeyRequest" do
      optional :meta, :message, 1, "v1.GetRequestMetadata"
    end
    add_message "v1.ControlPanelGetRDPCAPublicKeyResponse" do
      optional :meta, :message, 1, "v1.GetResponseMetadata"
      optional :public_key, :string, 2
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.ControlPanelVerifyJWTRequest" do
      optional :meta, :message, 1, "v1.GetRequestMetadata"
      optional :token, :string, 2
    end
    add_message "v1.ControlPanelVerifyJWTResponse" do
      optional :meta, :message, 1, "v1.GetResponseMetadata"
      optional :valid, :bool, 2
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.ControlPanelGetOrgURLInfoRequest" do
      optional :meta, :message, 1, "v1.GetRequestMetadata"
    end
    add_message "v1.ControlPanelGetOrgURLInfoResponse" do
      optional :meta, :message, 1, "v1.GetResponseMetadata"
      optional :base_url, :string, 2
      optional :websites_subdomain, :string, 3
      optional :oidc_issuer_url, :string, 4
      optional :saml_metadata_url, :string, 5
      optional :rate_limit, :message, 6, "v1.RateLimitMetadata"
    end
  end
end

module V1
  ControlPanelGetSSHCAPublicKeyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ControlPanelGetSSHCAPublicKeyRequest").msgclass
  ControlPanelGetSSHCAPublicKeyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ControlPanelGetSSHCAPublicKeyResponse").msgclass
  ControlPanelGetRDPCAPublicKeyRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ControlPanelGetRDPCAPublicKeyRequest").msgclass
  ControlPanelGetRDPCAPublicKeyResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ControlPanelGetRDPCAPublicKeyResponse").msgclass
  ControlPanelVerifyJWTRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ControlPanelVerifyJWTRequest").msgclass
  ControlPanelVerifyJWTResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ControlPanelVerifyJWTResponse").msgclass
  ControlPanelGetOrgURLInfoRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ControlPanelGetOrgURLInfoRequest").msgclass
  ControlPanelGetOrgURLInfoResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ControlPanelGetOrgURLInfoResponse").msgclass
end
