# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: custom_headers.proto

require "google/protobuf"

require "options_pb"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("custom_headers.proto", :syntax => :proto3) do
    add_message "v1.CustomHeaders" do
      repeated :custom_headers, :message, 1, "v1.CustomHeader"
    end
    add_message "v1.CustomHeader" do
      optional :name, :string, 1
      optional :value, :string, 2
      optional :secret, :bool, 3
    end
  end
end

module V1
  CustomHeaders = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.CustomHeaders").msgclass
  CustomHeader = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.CustomHeader").msgclass
end
