# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo_provisioning_requests.proto

require "google/protobuf"

require "options_pb"
require "spec_pb"
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("demo_provisioning_requests.proto", :syntax => :proto3) do
    add_message "v1.DemoProvisioningRequestCreateRequest" do
      optional :meta, :message, 1, "v1.CreateRequestMetadata"
      optional :demo_provisioning_request, :message, 2, "v1.DemoProvisioningRequest"
    end
    add_message "v1.DemoProvisioningRequestCreateResponse" do
      optional :meta, :message, 1, "v1.CreateResponseMetadata"
      optional :demo_provisioning_request, :message, 2, "v1.DemoProvisioningRequest"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.DemoProvisioningRequestDeleteRequest" do
      optional :meta, :message, 1, "v1.DeleteRequestMetadata"
      optional :id, :string, 2
    end
    add_message "v1.DemoProvisioningRequestDeleteResponse" do
      optional :meta, :message, 1, "v1.DeleteResponseMetadata"
      optional :rate_limit, :message, 2, "v1.RateLimitMetadata"
    end
    add_message "v1.DemoProvisioningRequestUpdateRequest" do
      optional :meta, :message, 1, "v1.UpdateRequestMetadata"
      optional :id, :string, 2
      optional :demo_provisioning_request, :message, 3, "v1.DemoProvisioningRequest"
    end
    add_message "v1.DemoProvisioningRequestUpdateResponse" do
      optional :meta, :message, 1, "v1.UpdateResponseMetadata"
      optional :demo_provisioning_request, :message, 2, "v1.DemoProvisioningRequest"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.DemoProvisioningRequestListForOrganizationRequest" do
      optional :meta, :message, 1, "v1.ListRequestMetadata"
      optional :filter, :string, 2
    end
    add_message "v1.DemoProvisioningRequestListForOrganizationResponse" do
      optional :meta, :message, 1, "v1.ListResponseMetadata"
      repeated :demo_provisioning_requests, :message, 2, "v1.DemoProvisioningRequest"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.DemoProvisioningRequestListAllRequest" do
      optional :meta, :message, 1, "v1.ListRequestMetadata"
      optional :filter, :string, 2
    end
    add_message "v1.DemoProvisioningRequestListAllResponse" do
      optional :meta, :message, 1, "v1.ListResponseMetadata"
      repeated :demo_provisioning_requests, :message, 2, "v1.DemoProvisioningRequest"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.DemoProvisioningRequest" do
      optional :id, :string, 1
      optional :request_type, :string, 2
      optional :creator_id, :string, 3
      optional :created_resource_id, :string, 4
      optional :created_node_id, :string, 5
      optional :access_key, :string, 6
      optional :secret_key, :string, 7
    end
  end
end

module V1
  DemoProvisioningRequestCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.DemoProvisioningRequestCreateRequest").msgclass
  DemoProvisioningRequestCreateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.DemoProvisioningRequestCreateResponse").msgclass
  DemoProvisioningRequestDeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.DemoProvisioningRequestDeleteRequest").msgclass
  DemoProvisioningRequestDeleteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.DemoProvisioningRequestDeleteResponse").msgclass
  DemoProvisioningRequestUpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.DemoProvisioningRequestUpdateRequest").msgclass
  DemoProvisioningRequestUpdateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.DemoProvisioningRequestUpdateResponse").msgclass
  DemoProvisioningRequestListForOrganizationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.DemoProvisioningRequestListForOrganizationRequest").msgclass
  DemoProvisioningRequestListForOrganizationResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.DemoProvisioningRequestListForOrganizationResponse").msgclass
  DemoProvisioningRequestListAllRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.DemoProvisioningRequestListAllRequest").msgclass
  DemoProvisioningRequestListAllResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.DemoProvisioningRequestListAllResponse").msgclass
  DemoProvisioningRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.DemoProvisioningRequest").msgclass
end
