# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discovery_connectors.proto

require "google/protobuf"

require "options_pb"
require "spec_pb"
require "tags_pb"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("discovery_connectors.proto", :syntax => :proto3) do
    add_message "v1.ConnectorCreateRequest" do
      optional :meta, :message, 1, "v1.CreateRequestMetadata"
      optional :connector, :message, 2, "v1.Connector"
    end
    add_message "v1.ConnectorCreateResponse" do
      optional :meta, :message, 1, "v1.CreateResponseMetadata"
      optional :connector, :message, 2, "v1.Connector"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.ConnectorGetRequest" do
      optional :meta, :message, 1, "v1.GetRequestMetadata"
      optional :id, :string, 2
    end
    add_message "v1.ConnectorGetResponse" do
      optional :meta, :message, 1, "v1.GetResponseMetadata"
      optional :connector, :message, 2, "v1.Connector"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.ConnectorUpdateRequest" do
      optional :meta, :message, 1, "v1.UpdateRequestMetadata"
      optional :id, :string, 2
      optional :connector, :message, 3, "v1.Connector"
    end
    add_message "v1.ConnectorUpdateResponse" do
      optional :meta, :message, 1, "v1.UpdateResponseMetadata"
      optional :connector, :message, 2, "v1.Connector"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.ConnectorDeleteRequest" do
      optional :meta, :message, 1, "v1.DeleteRequestMetadata"
      optional :id, :string, 2
    end
    add_message "v1.ConnectorDeleteResponse" do
      optional :meta, :message, 1, "v1.DeleteResponseMetadata"
      optional :rate_limit, :message, 2, "v1.RateLimitMetadata"
    end
    add_message "v1.ConnectorListRequest" do
      optional :meta, :message, 1, "v1.ListRequestMetadata"
      optional :filter, :string, 2
    end
    add_message "v1.ConnectorListResponse" do
      optional :meta, :message, 1, "v1.ListResponseMetadata"
      repeated :connectors, :message, 2, "v1.Connector"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.Connector" do
      oneof :cloud do
        optional :aws, :message, 100, "v1.AWSConnector"
        optional :azure, :message, 101, "v1.AzureConnector"
        optional :gcp, :message, 102, "v1.GCPConnector"
      end
    end
    add_message "v1.AWSConnector" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :description, :string, 3
      optional :scan_period, :string, 4
      repeated :services, :string, 5
      repeated :include_tags, :message, 6, "v1.Tag"
      repeated :exclude_tags, :message, 7, "v1.Tag"
      optional :role_name, :string, 20
      repeated :account_ids, :string, 21
    end
    add_message "v1.AzureConnector" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :description, :string, 3
      optional :scan_period, :string, 4
      repeated :services, :string, 5
      repeated :include_tags, :message, 6, "v1.Tag"
      repeated :exclude_tags, :message, 7, "v1.Tag"
      optional :tenant_id, :string, 20
      optional :client_id, :string, 21
      repeated :subscription_ids, :string, 22
    end
    add_message "v1.GCPConnector" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :description, :string, 3
      optional :scan_period, :string, 4
      repeated :services, :string, 5
      repeated :include_tags, :message, 6, "v1.Tag"
      repeated :exclude_tags, :message, 7, "v1.Tag"
      repeated :project_ids, :string, 23
      optional :workload_project_number, :string, 24
      optional :workload_project_id, :string, 25
      optional :workload_provider_id, :string, 26
      optional :workload_pool_id, :string, 27
    end
  end
end

module V1
  ConnectorCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ConnectorCreateRequest").msgclass
  ConnectorCreateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ConnectorCreateResponse").msgclass
  ConnectorGetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ConnectorGetRequest").msgclass
  ConnectorGetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ConnectorGetResponse").msgclass
  ConnectorUpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ConnectorUpdateRequest").msgclass
  ConnectorUpdateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ConnectorUpdateResponse").msgclass
  ConnectorDeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ConnectorDeleteRequest").msgclass
  ConnectorDeleteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ConnectorDeleteResponse").msgclass
  ConnectorListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ConnectorListRequest").msgclass
  ConnectorListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ConnectorListResponse").msgclass
  Connector = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.Connector").msgclass
  AWSConnector = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AWSConnector").msgclass
  AzureConnector = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.AzureConnector").msgclass
  GCPConnector = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.GCPConnector").msgclass
end
