# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: granted_role_entitlements.proto

require "google/protobuf"

require "google/protobuf/timestamp_pb"
require "options_pb"
require "spec_pb"
require "granted_account_entitlements_pb"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("granted_role_entitlements.proto", :syntax => :proto3) do
    add_message "v1.GrantedRoleEntitlementListRequest" do
      optional :meta, :message, 1, "v1.ListRequestMetadata"
      optional :role_id, :string, 2
      optional :filter, :string, 3
    end
    add_message "v1.GrantedRoleEntitlementListResponse" do
      optional :meta, :message, 1, "v1.ListResponseMetadata"
      repeated :granted_role_entitlements, :message, 2, "v1.GrantedRoleEntitlement"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.GrantedRoleEntitlement" do
      optional :resource_id, :string, 1
      optional :last_accessed, :message, 2, "google.protobuf.Timestamp"
      optional :mapped_identities, :message, 3, "v1.MappedIdentities"
      optional :group_id, :string, 4
    end
  end
end

module V1
  GrantedRoleEntitlementListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.GrantedRoleEntitlementListRequest").msgclass
  GrantedRoleEntitlementListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.GrantedRoleEntitlementListResponse").msgclass
  GrantedRoleEntitlement = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.GrantedRoleEntitlement").msgclass
end
