# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: groups_roles.proto for package 'v1'

require "grpc"
require "groups_roles_pb"

module V1
  module GroupsRoles
    # A GroupRole is an assignment of a Group to a Role.
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "v1.GroupsRoles"

      # Create registers a new GroupRole.
      rpc :Create, ::V1::GroupRoleCreateRequest, ::V1::GroupRoleCreateResponse
      # Get reads one GroupRole by ID.
      rpc :Get, ::V1::GroupRoleGetRequest, ::V1::GroupRoleGetResponse
      # Delete removes a GroupRole by ID.
      rpc :Delete, ::V1::GroupRoleDeleteRequest, ::V1::GroupRoleDeleteResponse
      # List gets a list of GroupRoles matching a given set of criteria.
      rpc :List, ::V1::GroupRoleListRequest, ::V1::GroupRoleListResponse
    end

    Stub = Service.rpc_stub_class
  end
end
