# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: groups_roles.proto

require "google/protobuf"

require "options_pb"
require "spec_pb"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("groups_roles.proto", :syntax => :proto3) do
    add_message "v1.GroupRoleCreateRequest" do
      optional :meta, :message, 1, "v1.CreateRequestMetadata"
      optional :group_role, :message, 2, "v1.GroupRole"
    end
    add_message "v1.GroupRoleCreateResponse" do
      optional :meta, :message, 1, "v1.CreateResponseMetadata"
      optional :group_role, :message, 2, "v1.GroupRole"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.GroupRoleGetRequest" do
      optional :meta, :message, 1, "v1.GetRequestMetadata"
      optional :id, :string, 2
    end
    add_message "v1.GroupRoleGetResponse" do
      optional :meta, :message, 1, "v1.GetResponseMetadata"
      optional :group_role, :message, 2, "v1.GroupRole"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.GroupRoleDeleteRequest" do
      optional :meta, :message, 1, "v1.DeleteRequestMetadata"
      optional :id, :string, 2
    end
    add_message "v1.GroupRoleDeleteResponse" do
      optional :meta, :message, 1, "v1.DeleteResponseMetadata"
      optional :rate_limit, :message, 2, "v1.RateLimitMetadata"
      optional :group_role, :message, 3, "v1.GroupRole"
    end
    add_message "v1.GroupRoleListRequest" do
      optional :meta, :message, 1, "v1.ListRequestMetadata"
      optional :filter, :string, 2
    end
    add_message "v1.GroupRoleListResponse" do
      optional :meta, :message, 1, "v1.ListResponseMetadata"
      repeated :groups_roles, :message, 2, "v1.GroupRole"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.GroupRole" do
      optional :id, :string, 1
      optional :group_id, :string, 2
      optional :role_id, :string, 3
      optional :group_name, :string, 4
      optional :role_name, :string, 5
    end
  end
end

module V1
  GroupRoleCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.GroupRoleCreateRequest").msgclass
  GroupRoleCreateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.GroupRoleCreateResponse").msgclass
  GroupRoleGetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.GroupRoleGetRequest").msgclass
  GroupRoleGetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.GroupRoleGetResponse").msgclass
  GroupRoleDeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.GroupRoleDeleteRequest").msgclass
  GroupRoleDeleteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.GroupRoleDeleteResponse").msgclass
  GroupRoleListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.GroupRoleListRequest").msgclass
  GroupRoleListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.GroupRoleListResponse").msgclass
  GroupRole = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.GroupRole").msgclass
end
