# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: health_checks.proto for package 'v1'

require "grpc"
require "health_checks_pb"

module V1
  module HealthChecks
    # HealthChecks lists the last healthcheck between each node and resource.
    # Note the unconventional capitalization here is to prevent having a collision with GRPC
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "v1.HealthChecks"

      # List gets a list of Healthchecks matching a given set of criteria.
      rpc :List, ::V1::HealthcheckListRequest, ::V1::HealthcheckListResponse
    end

    Stub = Service.rpc_stub_class
  end
end
