# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: identity_aliases.proto for package 'v1'

require "grpc"
require "identity_aliases_pb"

module V1
  module IdentityAliases
    # IdentityAliases assign an alias to an account within an IdentitySet.
    # The alias is used as the username when connecting to a identity supported resource.
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "v1.IdentityAliases"

      # Create registers a new IdentityAlias.
      rpc :Create, ::V1::IdentityAliasCreateRequest, ::V1::IdentityAliasCreateResponse
      # Get reads one IdentityAlias by ID.
      rpc :Get, ::V1::IdentityAliasGetRequest, ::V1::IdentityAliasGetResponse
      # Update replaces all the fields of a IdentityAlias by ID.
      rpc :Update, ::V1::IdentityAliasUpdateRequest, ::V1::IdentityAliasUpdateResponse
      # Delete removes a IdentityAlias by ID.
      rpc :Delete, ::V1::IdentityAliasDeleteRequest, ::V1::IdentityAliasDeleteResponse
      # List gets a list of IdentityAliases matching a given set of criteria.
      rpc :List, ::V1::IdentityAliasListRequest, ::V1::IdentityAliasListResponse
    end

    Stub = Service.rpc_stub_class
  end
end
