# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: location_enums.proto

require "google/protobuf"

require "options_pb"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("location_enums.proto", :syntax => :proto3) do
    add_enum "v1.LocationContinent" do
      value :LOCATION_CONTINENT_UNSPECIFIED, 0
      value :LOCATION_CONTINENT_AF, 1
      value :LOCATION_CONTINENT_AN, 2
      value :LOCATION_CONTINENT_AS, 3
      value :LOCATION_CONTINENT_EU, 4
      value :LOCATION_CONTINENT_NA, 5
      value :LOCATION_CONTINENT_OC, 6
      value :LOCATION_CONTINENT_SA, 7
    end
    add_enum "v1.LocationCountry" do
      value :LOCATION_COUNTRY_UNSPECIFIED, 0
      value :LOCATION_COUNTRY_AD, 1
      value :LOCATION_COUNTRY_AE, 2
      value :LOCATION_COUNTRY_AF, 3
      value :LOCATION_COUNTRY_AG, 4
      value :LOCATION_COUNTRY_AI, 5
      value :LOCATION_COUNTRY_AL, 6
      value :LOCATION_COUNTRY_AM, 7
      value :LOCATION_COUNTRY_AO, 8
      value :LOCATION_COUNTRY_AQ, 9
      value :LOCATION_COUNTRY_AR, 10
      value :LOCATION_COUNTRY_AS, 11
      value :LOCATION_COUNTRY_AT, 12
      value :LOCATION_COUNTRY_AU, 13
      value :LOCATION_COUNTRY_AW, 14
      value :LOCATION_COUNTRY_AX, 15
      value :LOCATION_COUNTRY_AZ, 16
      value :LOCATION_COUNTRY_BA, 17
      value :LOCATION_COUNTRY_BB, 18
      value :LOCATION_COUNTRY_BD, 19
      value :LOCATION_COUNTRY_BE, 20
      value :LOCATION_COUNTRY_BF, 21
      value :LOCATION_COUNTRY_BG, 22
      value :LOCATION_COUNTRY_BH, 23
      value :LOCATION_COUNTRY_BI, 24
      value :LOCATION_COUNTRY_BJ, 25
      value :LOCATION_COUNTRY_BL, 26
      value :LOCATION_COUNTRY_BM, 27
      value :LOCATION_COUNTRY_BN, 28
      value :LOCATION_COUNTRY_BO, 29
      value :LOCATION_COUNTRY_BQ, 30
      value :LOCATION_COUNTRY_BR, 31
      value :LOCATION_COUNTRY_BS, 32
      value :LOCATION_COUNTRY_BT, 33
      value :LOCATION_COUNTRY_BV, 34
      value :LOCATION_COUNTRY_BW, 35
      value :LOCATION_COUNTRY_BY, 36
      value :LOCATION_COUNTRY_BZ, 37
      value :LOCATION_COUNTRY_CA, 38
      value :LOCATION_COUNTRY_CC, 39
      value :LOCATION_COUNTRY_CD, 40
      value :LOCATION_COUNTRY_CF, 41
      value :LOCATION_COUNTRY_CG, 42
      value :LOCATION_COUNTRY_CH, 43
      value :LOCATION_COUNTRY_CI, 44
      value :LOCATION_COUNTRY_CK, 45
      value :LOCATION_COUNTRY_CL, 46
      value :LOCATION_COUNTRY_CM, 47
      value :LOCATION_COUNTRY_CN, 48
      value :LOCATION_COUNTRY_CO, 49
      value :LOCATION_COUNTRY_CR, 50
      value :LOCATION_COUNTRY_CU, 51
      value :LOCATION_COUNTRY_CV, 52
      value :LOCATION_COUNTRY_CW, 53
      value :LOCATION_COUNTRY_CX, 54
      value :LOCATION_COUNTRY_CY, 55
      value :LOCATION_COUNTRY_CZ, 56
      value :LOCATION_COUNTRY_DE, 57
      value :LOCATION_COUNTRY_DJ, 58
      value :LOCATION_COUNTRY_DK, 59
      value :LOCATION_COUNTRY_DM, 60
      value :LOCATION_COUNTRY_DO, 61
      value :LOCATION_COUNTRY_DZ, 62
      value :LOCATION_COUNTRY_EC, 63
      value :LOCATION_COUNTRY_EE, 64
      value :LOCATION_COUNTRY_EG, 65
      value :LOCATION_COUNTRY_EH, 66
      value :LOCATION_COUNTRY_ER, 67
      value :LOCATION_COUNTRY_ES, 68
      value :LOCATION_COUNTRY_ET, 69
      value :LOCATION_COUNTRY_FI, 70
      value :LOCATION_COUNTRY_FJ, 71
      value :LOCATION_COUNTRY_FK, 72
      value :LOCATION_COUNTRY_FM, 73
      value :LOCATION_COUNTRY_FO, 74
      value :LOCATION_COUNTRY_FR, 75
      value :LOCATION_COUNTRY_GA, 76
      value :LOCATION_COUNTRY_GB, 77
      value :LOCATION_COUNTRY_GD, 78
      value :LOCATION_COUNTRY_GE, 79
      value :LOCATION_COUNTRY_GF, 80
      value :LOCATION_COUNTRY_GG, 81
      value :LOCATION_COUNTRY_GH, 82
      value :LOCATION_COUNTRY_GI, 83
      value :LOCATION_COUNTRY_GL, 84
      value :LOCATION_COUNTRY_GM, 85
      value :LOCATION_COUNTRY_GN, 86
      value :LOCATION_COUNTRY_GP, 87
      value :LOCATION_COUNTRY_GQ, 88
      value :LOCATION_COUNTRY_GR, 89
      value :LOCATION_COUNTRY_GS, 90
      value :LOCATION_COUNTRY_GT, 91
      value :LOCATION_COUNTRY_GU, 92
      value :LOCATION_COUNTRY_GW, 93
      value :LOCATION_COUNTRY_GY, 94
      value :LOCATION_COUNTRY_HK, 95
      value :LOCATION_COUNTRY_HM, 96
      value :LOCATION_COUNTRY_HN, 97
      value :LOCATION_COUNTRY_HR, 98
      value :LOCATION_COUNTRY_HT, 99
      value :LOCATION_COUNTRY_HU, 100
      value :LOCATION_COUNTRY_ID, 101
      value :LOCATION_COUNTRY_IE, 102
      value :LOCATION_COUNTRY_IL, 103
      value :LOCATION_COUNTRY_IM, 104
      value :LOCATION_COUNTRY_IN, 105
      value :LOCATION_COUNTRY_IO, 106
      value :LOCATION_COUNTRY_IQ, 107
      value :LOCATION_COUNTRY_IR, 108
      value :LOCATION_COUNTRY_IS, 109
      value :LOCATION_COUNTRY_IT, 110
      value :LOCATION_COUNTRY_JE, 111
      value :LOCATION_COUNTRY_JM, 112
      value :LOCATION_COUNTRY_JO, 113
      value :LOCATION_COUNTRY_JP, 114
      value :LOCATION_COUNTRY_KE, 115
      value :LOCATION_COUNTRY_KG, 116
      value :LOCATION_COUNTRY_KH, 117
      value :LOCATION_COUNTRY_KI, 118
      value :LOCATION_COUNTRY_KM, 119
      value :LOCATION_COUNTRY_KN, 120
      value :LOCATION_COUNTRY_KP, 121
      value :LOCATION_COUNTRY_KR, 122
      value :LOCATION_COUNTRY_KW, 123
      value :LOCATION_COUNTRY_KY, 124
      value :LOCATION_COUNTRY_KZ, 125
      value :LOCATION_COUNTRY_LA, 126
      value :LOCATION_COUNTRY_LB, 127
      value :LOCATION_COUNTRY_LC, 128
      value :LOCATION_COUNTRY_LI, 129
      value :LOCATION_COUNTRY_LK, 130
      value :LOCATION_COUNTRY_LR, 131
      value :LOCATION_COUNTRY_LS, 132
      value :LOCATION_COUNTRY_LT, 133
      value :LOCATION_COUNTRY_LU, 134
      value :LOCATION_COUNTRY_LV, 135
      value :LOCATION_COUNTRY_LY, 136
      value :LOCATION_COUNTRY_MA, 137
      value :LOCATION_COUNTRY_MC, 138
      value :LOCATION_COUNTRY_MD, 139
      value :LOCATION_COUNTRY_ME, 140
      value :LOCATION_COUNTRY_MF, 141
      value :LOCATION_COUNTRY_MG, 142
      value :LOCATION_COUNTRY_MH, 143
      value :LOCATION_COUNTRY_MK, 144
      value :LOCATION_COUNTRY_ML, 145
      value :LOCATION_COUNTRY_MM, 146
      value :LOCATION_COUNTRY_MN, 147
      value :LOCATION_COUNTRY_MO, 148
      value :LOCATION_COUNTRY_MP, 149
      value :LOCATION_COUNTRY_MQ, 150
      value :LOCATION_COUNTRY_MR, 151
      value :LOCATION_COUNTRY_MS, 152
      value :LOCATION_COUNTRY_MT, 153
      value :LOCATION_COUNTRY_MU, 154
      value :LOCATION_COUNTRY_MV, 155
      value :LOCATION_COUNTRY_MW, 156
      value :LOCATION_COUNTRY_MX, 157
      value :LOCATION_COUNTRY_MY, 158
      value :LOCATION_COUNTRY_MZ, 159
      value :LOCATION_COUNTRY_NA, 160
      value :LOCATION_COUNTRY_NC, 161
      value :LOCATION_COUNTRY_NE, 162
      value :LOCATION_COUNTRY_NF, 163
      value :LOCATION_COUNTRY_NG, 164
      value :LOCATION_COUNTRY_NI, 165
      value :LOCATION_COUNTRY_NL, 166
      value :LOCATION_COUNTRY_NO, 167
      value :LOCATION_COUNTRY_NP, 168
      value :LOCATION_COUNTRY_NR, 169
      value :LOCATION_COUNTRY_NU, 170
      value :LOCATION_COUNTRY_NZ, 171
      value :LOCATION_COUNTRY_OM, 172
      value :LOCATION_COUNTRY_PA, 173
      value :LOCATION_COUNTRY_PE, 174
      value :LOCATION_COUNTRY_PF, 175
      value :LOCATION_COUNTRY_PG, 176
      value :LOCATION_COUNTRY_PH, 177
      value :LOCATION_COUNTRY_PK, 178
      value :LOCATION_COUNTRY_PL, 179
      value :LOCATION_COUNTRY_PM, 180
      value :LOCATION_COUNTRY_PN, 181
      value :LOCATION_COUNTRY_PR, 182
      value :LOCATION_COUNTRY_PS, 183
      value :LOCATION_COUNTRY_PT, 184
      value :LOCATION_COUNTRY_PW, 185
      value :LOCATION_COUNTRY_PY, 186
      value :LOCATION_COUNTRY_QA, 187
      value :LOCATION_COUNTRY_RE, 188
      value :LOCATION_COUNTRY_RO, 189
      value :LOCATION_COUNTRY_RS, 190
      value :LOCATION_COUNTRY_RU, 191
      value :LOCATION_COUNTRY_RW, 192
      value :LOCATION_COUNTRY_SA, 193
      value :LOCATION_COUNTRY_SB, 194
      value :LOCATION_COUNTRY_SC, 195
      value :LOCATION_COUNTRY_SD, 196
      value :LOCATION_COUNTRY_SE, 197
      value :LOCATION_COUNTRY_SG, 198
      value :LOCATION_COUNTRY_SH, 199
      value :LOCATION_COUNTRY_SI, 200
      value :LOCATION_COUNTRY_SJ, 201
      value :LOCATION_COUNTRY_SK, 202
      value :LOCATION_COUNTRY_SL, 203
      value :LOCATION_COUNTRY_SM, 204
      value :LOCATION_COUNTRY_SN, 205
      value :LOCATION_COUNTRY_SO, 206
      value :LOCATION_COUNTRY_SR, 207
      value :LOCATION_COUNTRY_SS, 208
      value :LOCATION_COUNTRY_ST, 209
      value :LOCATION_COUNTRY_SV, 210
      value :LOCATION_COUNTRY_SX, 211
      value :LOCATION_COUNTRY_SY, 212
      value :LOCATION_COUNTRY_SZ, 213
      value :LOCATION_COUNTRY_TC, 214
      value :LOCATION_COUNTRY_TD, 215
      value :LOCATION_COUNTRY_TF, 216
      value :LOCATION_COUNTRY_TG, 217
      value :LOCATION_COUNTRY_TH, 218
      value :LOCATION_COUNTRY_TJ, 219
      value :LOCATION_COUNTRY_TK, 220
      value :LOCATION_COUNTRY_TL, 221
      value :LOCATION_COUNTRY_TM, 222
      value :LOCATION_COUNTRY_TN, 223
      value :LOCATION_COUNTRY_TO, 224
      value :LOCATION_COUNTRY_TR, 225
      value :LOCATION_COUNTRY_TT, 226
      value :LOCATION_COUNTRY_TV, 227
      value :LOCATION_COUNTRY_TW, 228
      value :LOCATION_COUNTRY_TZ, 229
      value :LOCATION_COUNTRY_UA, 230
      value :LOCATION_COUNTRY_UG, 231
      value :LOCATION_COUNTRY_UM, 232
      value :LOCATION_COUNTRY_US, 233
      value :LOCATION_COUNTRY_UY, 234
      value :LOCATION_COUNTRY_UZ, 235
      value :LOCATION_COUNTRY_VA, 236
      value :LOCATION_COUNTRY_VC, 237
      value :LOCATION_COUNTRY_VE, 238
      value :LOCATION_COUNTRY_VG, 239
      value :LOCATION_COUNTRY_VI, 240
      value :LOCATION_COUNTRY_VN, 241
      value :LOCATION_COUNTRY_VU, 242
      value :LOCATION_COUNTRY_WF, 243
      value :LOCATION_COUNTRY_WS, 244
      value :LOCATION_COUNTRY_YE, 245
      value :LOCATION_COUNTRY_YT, 246
      value :LOCATION_COUNTRY_ZA, 247
      value :LOCATION_COUNTRY_ZM, 248
      value :LOCATION_COUNTRY_ZW, 249
    end
  end
end

module V1
  LocationContinent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.LocationContinent").enummodule
  LocationCountry = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.LocationCountry").enummodule
end
