# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: managed_secrets.proto for package 'v1'

require "grpc"
require "managed_secrets_pb"

module V1
  module ManagedSecrets
    # ManagedSecret is a private vertical for creating, reading, updating,
    # deleting, listing and rotating the managed secrets in the secrets engines as
    # an authenticated user.
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "v1.ManagedSecrets"

      # List returns Managed Secrets from a Secret Engine.
      rpc :List, ::V1::ManagedSecretListRequest, ::V1::ManagedSecretListResponse
      # List returns Managed Secrets for an Actor from a Secret Engine.
      rpc :ListByActor, ::V1::ManagedSecretListRequest, ::V1::ManagedSecretListResponse
      # Create creates a Managed Secret
      rpc :Create, ::V1::ManagedSecretCreateRequest, ::V1::ManagedSecretCreateResponse
      # Update updates a Managed Secret
      rpc :Update, ::V1::ManagedSecretUpdateRequest, ::V1::ManagedSecretUpdateResponse
      # Rotate forces rotation of Managed Secret
      rpc :Rotate, ::V1::ManagedSecretRotateRequest, ::V1::ManagedSecretRotateResponse
      # Delete deletes a Managed Secret
      rpc :Delete, ::V1::ManagedSecretDeleteRequest, ::V1::ManagedSecretDeleteResponse
      # Get gets details of a Managed Secret without sensitive data
      rpc :Get, ::V1::ManagedSecretGetRequest, ::V1::ManagedSecretGetResponse
      # Retrieve returns Managed Secret with sensitive data
      rpc :Retrieve, ::V1::ManagedSecretRetrieveRequest, ::V1::ManagedSecretRetrieveResponse
      # Validate returns the result of testing the stored credential against the
      # secret engine.
      rpc :Validate, ::V1::ManagedSecretValidateRequest, ::V1::ManagedSecretValidateResponse
      # Logs returns the audit records for the managed secret. This may be replaced
      # in the future.
      rpc :Logs, ::V1::ManagedSecretLogsRequest, ::V1::ManagedSecretLogsResponse
    end

    Stub = Service.rpc_stub_class
  end
end
