# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: organizations.proto

require "google/protobuf"

require "organization_history_pb"
require "options_pb"
require "spec_pb"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("organizations.proto", :syntax => :proto3) do
    add_message "v1.OrganizationUpdateRequest" do
      optional :meta, :message, 1, "v1.UpdateRequestMetadata"
      optional :organization, :message, 2, "v1.Organization"
    end
    add_message "v1.OrganizationUpdateResponse" do
      optional :meta, :message, 1, "v1.UpdateResponseMetadata"
      optional :organization, :message, 2, "v1.Organization"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.OrganizationGetRequest" do
      optional :meta, :message, 1, "v1.GetRequestMetadata"
    end
    add_message "v1.OrganizationGetResponse" do
      optional :meta, :message, 1, "v1.GetResponseMetadata"
      optional :organization, :message, 2, "v1.Organization"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.MFAConfig" do
      optional :enabled, :bool, 1
      optional :provider, :string, 2
      optional :okta, :message, 3, "v1.OktaMFAConfig"
    end
    add_message "v1.OktaMFAConfig" do
      optional :auth_mode, :string, 1
      optional :api_token, :string, 2
      optional :api_token_set, :bool, 3
      optional :client_id, :string, 4
      optional :private_key_pem, :string, 5
      optional :private_key_pem_set, :bool, 6
      optional :organization_url, :string, 7
      optional :multidevice_push_enabled, :bool, 8
      optional :user_lookup, :string, 9
      optional :private_key_id, :string, 10
      optional :private_key_id_set, :bool, 11
    end
    add_message "v1.OrganizationGetMFARequest" do
      optional :meta, :message, 1, "v1.GetRequestMetadata"
    end
    add_message "v1.OrganizationGetMFAResponse" do
      optional :meta, :message, 1, "v1.GetResponseMetadata"
      optional :mfa, :message, 2, "v1.MFAConfig"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.OrganizationUpdateMFARequest" do
      optional :meta, :message, 1, "v1.UpdateRequestMetadata"
      optional :mfa, :message, 2, "v1.MFAConfig"
    end
    add_message "v1.OrganizationUpdateMFAResponse" do
      optional :meta, :message, 1, "v1.UpdateResponseMetadata"
      optional :mfa, :message, 2, "v1.MFAConfig"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.OrganizationTestMFARequest" do
      optional :meta, :message, 1, "v1.UpdateRequestMetadata"
      optional :mfa, :message, 2, "v1.MFAConfig"
    end
    add_message "v1.OrganizationTestMFAResponse" do
      optional :meta, :message, 1, "v1.UpdateResponseMetadata"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
  end
end

module V1
  OrganizationUpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.OrganizationUpdateRequest").msgclass
  OrganizationUpdateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.OrganizationUpdateResponse").msgclass
  OrganizationGetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.OrganizationGetRequest").msgclass
  OrganizationGetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.OrganizationGetResponse").msgclass
  MFAConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.MFAConfig").msgclass
  OktaMFAConfig = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.OktaMFAConfig").msgclass
  OrganizationGetMFARequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.OrganizationGetMFARequest").msgclass
  OrganizationGetMFAResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.OrganizationGetMFAResponse").msgclass
  OrganizationUpdateMFARequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.OrganizationUpdateMFARequest").msgclass
  OrganizationUpdateMFAResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.OrganizationUpdateMFAResponse").msgclass
  OrganizationTestMFARequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.OrganizationTestMFARequest").msgclass
  OrganizationTestMFAResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.OrganizationTestMFAResponse").msgclass
end
