# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: organizations.proto for package 'v1'

require "grpc"
require "organizations_pb"

module V1
  module Organizations
    # Organizations exposes organization configuration. Most RPCs remain private to the
    # go_private SDK; public MFA management is exposed to all public SDK targets.
    # The terraform-provider target is opted out at the service level because the
    # provider's data-source generator assumes every service has a List RPC; MFA is
    # instead surfaced via a hand-written resource template.
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "v1.Organizations"

      # Update updates an existing organization.
      rpc :Update, ::V1::OrganizationUpdateRequest, ::V1::OrganizationUpdateResponse
      # Get gets an organization
      rpc :Get, ::V1::OrganizationGetRequest, ::V1::OrganizationGetResponse
      # GetMFA gets the organization's MFA configuration.
      rpc :GetMFA, ::V1::OrganizationGetMFARequest, ::V1::OrganizationGetMFAResponse
      # UpdateMFA updates the organization's MFA configuration.
      rpc :UpdateMFA, ::V1::OrganizationUpdateMFARequest, ::V1::OrganizationUpdateMFAResponse
      # TestMFA validates MFA connectivity without persisting changes.
      rpc :TestMFA, ::V1::OrganizationTestMFARequest, ::V1::OrganizationTestMFAResponse
    end

    Stub = Service.rpc_stub_class
  end
end
