# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peering_group_resources.proto

require "google/protobuf"

require "options_pb"
require "spec_pb"
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("peering_group_resources.proto", :syntax => :proto3) do
    add_message "v1.PeeringGroupResourceCreateRequest" do
      optional :meta, :message, 1, "v1.CreateRequestMetadata"
      optional :peering_group_resource, :message, 2, "v1.PeeringGroupResource"
    end
    add_message "v1.PeeringGroupResourceCreateResponse" do
      optional :meta, :message, 1, "v1.CreateResponseMetadata"
      optional :peering_group_resource, :message, 2, "v1.PeeringGroupResource"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.PeeringGroupResourceGetRequest" do
      optional :meta, :message, 1, "v1.GetRequestMetadata"
      optional :id, :string, 2
    end
    add_message "v1.PeeringGroupResourceGetResponse" do
      optional :meta, :message, 1, "v1.GetResponseMetadata"
      optional :peering_group_resource, :message, 2, "v1.PeeringGroupResource"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.PeeringGroupResourceDeleteRequest" do
      optional :meta, :message, 1, "v1.DeleteRequestMetadata"
      optional :id, :string, 2
    end
    add_message "v1.PeeringGroupResourceDeleteResponse" do
      optional :meta, :message, 1, "v1.DeleteResponseMetadata"
      optional :rate_limit, :message, 2, "v1.RateLimitMetadata"
    end
    add_message "v1.PeeringGroupResourceListRequest" do
      optional :meta, :message, 1, "v1.ListRequestMetadata"
      optional :filter, :string, 2
    end
    add_message "v1.PeeringGroupResourceListResponse" do
      optional :meta, :message, 1, "v1.ListResponseMetadata"
      repeated :peering_group_resources, :message, 2, "v1.PeeringGroupResource"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.PeeringGroupResource" do
      optional :id, :string, 1
      optional :resource_id, :string, 3
      optional :group_id, :string, 4
    end
  end
end

module V1
  PeeringGroupResourceCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PeeringGroupResourceCreateRequest").msgclass
  PeeringGroupResourceCreateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PeeringGroupResourceCreateResponse").msgclass
  PeeringGroupResourceGetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PeeringGroupResourceGetRequest").msgclass
  PeeringGroupResourceGetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PeeringGroupResourceGetResponse").msgclass
  PeeringGroupResourceDeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PeeringGroupResourceDeleteRequest").msgclass
  PeeringGroupResourceDeleteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PeeringGroupResourceDeleteResponse").msgclass
  PeeringGroupResourceListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PeeringGroupResourceListRequest").msgclass
  PeeringGroupResourceListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PeeringGroupResourceListResponse").msgclass
  PeeringGroupResource = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PeeringGroupResource").msgclass
end
