# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: peering_groups.proto for package 'v1'

require "grpc"
require "peering_groups_pb"

module V1
  module PeeringGroups
    # PeeringGroups provides the building blocks necessary to obtain explicit network topology and routing.
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "v1.PeeringGroups"

      # Create registers a new PeeringGroup.
      rpc :Create, ::V1::PeeringGroupCreateRequest, ::V1::PeeringGroupCreateResponse
      # Delete removes a PeeringGroup by ID.
      rpc :Delete, ::V1::PeeringGroupDeleteRequest, ::V1::PeeringGroupDeleteResponse
      # Get reads one PeeringGroup by ID. It will load all its dependencies.
      rpc :Get, ::V1::PeeringGroupGetRequest, ::V1::PeeringGroupGetResponse
      # List gets a list of Peering Groups.
      rpc :List, ::V1::PeeringGroupListRequest, ::V1::PeeringGroupListResponse
    end

    Stub = Service.rpc_stub_class
  end
end
