# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: policies.proto

require "google/protobuf"

require "options_pb"
require "spec_pb"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("policies.proto", :syntax => :proto3) do
    add_message "v1.PolicyCreateRequest" do
      optional :meta, :message, 1, "v1.CreateRequestMetadata"
      optional :policy, :message, 2, "v1.Policy"
    end
    add_message "v1.PolicyCreateResponse" do
      optional :meta, :message, 1, "v1.CreateResponseMetadata"
      optional :policy, :message, 2, "v1.Policy"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.PolicyUpdateRequest" do
      optional :meta, :message, 1, "v1.UpdateRequestMetadata"
      optional :id, :string, 2
      optional :policy, :message, 3, "v1.Policy"
    end
    add_message "v1.PolicyUpdateResponse" do
      optional :meta, :message, 1, "v1.UpdateResponseMetadata"
      optional :policy, :message, 2, "v1.Policy"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.PolicyDeleteRequest" do
      optional :meta, :message, 1, "v1.DeleteRequestMetadata"
      optional :id, :string, 2
    end
    add_message "v1.PolicyDeleteResponse" do
      optional :meta, :message, 1, "v1.DeleteResponseMetadata"
      optional :rate_limit, :message, 2, "v1.RateLimitMetadata"
    end
    add_message "v1.PolicyGetRequest" do
      optional :meta, :message, 1, "v1.GetRequestMetadata"
      optional :id, :string, 2
    end
    add_message "v1.PolicyGetResponse" do
      optional :meta, :message, 1, "v1.GetResponseMetadata"
      optional :policy, :message, 2, "v1.Policy"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.PolicyListRequest" do
      optional :meta, :message, 1, "v1.ListRequestMetadata"
      optional :filter, :string, 2
    end
    add_message "v1.PolicyListResponse" do
      optional :meta, :message, 1, "v1.ListResponseMetadata"
      repeated :policies, :message, 2, "v1.Policy"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.Policy" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :description, :string, 3
      optional :policy, :string, 4
    end
  end
end

module V1
  PolicyCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PolicyCreateRequest").msgclass
  PolicyCreateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PolicyCreateResponse").msgclass
  PolicyUpdateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PolicyUpdateRequest").msgclass
  PolicyUpdateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PolicyUpdateResponse").msgclass
  PolicyDeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PolicyDeleteRequest").msgclass
  PolicyDeleteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PolicyDeleteResponse").msgclass
  PolicyGetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PolicyGetRequest").msgclass
  PolicyGetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PolicyGetResponse").msgclass
  PolicyListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PolicyListRequest").msgclass
  PolicyListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.PolicyListResponse").msgclass
  Policy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.Policy").msgclass
end
