# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: policies.proto for package 'v1'

require "grpc"
require "policies_pb"

module V1
  module Policies
    # Policies are the collection of one or more statements that enforce fine-grained access
    # control for the users of an organization.
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "v1.Policies"

      # Create creates a new Policy.
      rpc :Create, ::V1::PolicyCreateRequest, ::V1::PolicyCreateResponse
      # Delete removes a Policy by ID.
      rpc :Delete, ::V1::PolicyDeleteRequest, ::V1::PolicyDeleteResponse
      # Update replaces all the fields of a Policy by ID.
      rpc :Update, ::V1::PolicyUpdateRequest, ::V1::PolicyUpdateResponse
      # Get reads one Policy by ID.
      rpc :Get, ::V1::PolicyGetRequest, ::V1::PolicyGetResponse
      # List gets a list of Policy matching a given set of criteria
      rpc :List, ::V1::PolicyListRequest, ::V1::PolicyListResponse
    end

    Stub = Service.rpc_stub_class
  end
end
