# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: queries.proto

require "google/protobuf"

require "google/protobuf/duration_pb"
require "google/protobuf/timestamp_pb"
require "options_pb"
require "spec_pb"
require "tags_pb"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("queries.proto", :syntax => :proto3) do
    add_message "v1.QueryListRequest" do
      optional :meta, :message, 1, "v1.ListRequestMetadata"
      optional :filter, :string, 2
    end
    add_message "v1.QueryListResponse" do
      optional :meta, :message, 1, "v1.ListResponseMetadata"
      repeated :queries, :message, 2, "v1.Query"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.Query" do
      optional :id, :string, 1
      optional :account_id, :string, 2
      optional :resource_id, :string, 3
      optional :query_body, :string, 4
      optional :duration, :message, 5, "google.protobuf.Duration"
      optional :encrypted, :bool, 6
      optional :query_hash, :string, 7
      optional :remote_identity_username, :string, 8
      optional :timestamp, :message, 9, "google.protobuf.Timestamp"
      optional :egress_node_id, :string, 10
      optional :replayable, :bool, 11
      optional :record_count, :int64, 12
      optional :resource_type, :string, 13
      optional :query_category, :string, 14
      optional :query_key, :string, 15
      optional :resource_name, :string, 16
      optional :resource_tags, :message, 17, "v1.Tags"
      optional :account_first_name, :string, 18
      optional :account_last_name, :string, 19
      optional :account_email, :string, 20
      optional :account_tags, :message, 21, "v1.Tags"
      optional :query_key_id, :string, 22
      optional :completed_at, :message, 23, "google.protobuf.Timestamp"
      optional :capture, :message, 24, "v1.QueryCapture"
      optional :source_ip, :string, 25
      optional :authentication_id, :string, 26
      optional :target, :string, 27
      optional :authzJson, :string, 28
      optional :client_ip, :string, 29
      optional :identity_alias_username, :string, 30
    end
    add_message "v1.QueryCapture" do
      optional :width, :int32, 1
      optional :height, :int32, 2
      optional :command, :string, 3
      map :env, :string, :string, 4
      optional :type, :string, 5
      optional :file_name, :string, 6
      optional :file_size, :int64, 7
      optional :client_command, :string, 8
      optional :pod, :string, 9
      optional :container, :string, 10
      optional :request_method, :string, 11
      optional :request_uri, :string, 12
      optional :request_body, :bytes, 13
      optional :impersonation_user, :string, 14
      repeated :impersonation_groups, :string, 15
    end
  end
end

module V1
  QueryListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.QueryListRequest").msgclass
  QueryListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.QueryListResponse").msgclass
  Query = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.Query").msgclass
  QueryCapture = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.QueryCapture").msgclass
end
