# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_identity_groups.proto

require "google/protobuf"

require "options_pb"
require "spec_pb"
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("remote_identity_groups.proto", :syntax => :proto3) do
    add_message "v1.RemoteIdentityGroupGetRequest" do
      optional :meta, :message, 1, "v1.GetRequestMetadata"
      optional :id, :string, 2
    end
    add_message "v1.RemoteIdentityGroupGetResponse" do
      optional :meta, :message, 1, "v1.GetResponseMetadata"
      optional :remote_identity_group, :message, 2, "v1.RemoteIdentityGroup"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.RemoteIdentityGroupListRequest" do
      optional :meta, :message, 1, "v1.ListRequestMetadata"
      optional :filter, :string, 2
    end
    add_message "v1.RemoteIdentityGroupListResponse" do
      optional :meta, :message, 1, "v1.ListResponseMetadata"
      repeated :remote_identity_groups, :message, 2, "v1.RemoteIdentityGroup"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.RemoteIdentityGroup" do
      optional :id, :string, 1
      optional :name, :string, 2
    end
  end
end

module V1
  RemoteIdentityGroupGetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.RemoteIdentityGroupGetRequest").msgclass
  RemoteIdentityGroupGetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.RemoteIdentityGroupGetResponse").msgclass
  RemoteIdentityGroupListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.RemoteIdentityGroupListRequest").msgclass
  RemoteIdentityGroupListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.RemoteIdentityGroupListResponse").msgclass
  RemoteIdentityGroup = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.RemoteIdentityGroup").msgclass
end
