# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: replays.proto

require "google/protobuf"

require "google/protobuf/duration_pb"
require "options_pb"
require "spec_pb"

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("replays.proto", :syntax => :proto3) do
    add_message "v1.ReplayListRequest" do
      optional :meta, :message, 1, "v1.ListRequestMetadata"
      optional :filter, :string, 2
    end
    add_message "v1.ReplayListResponse" do
      optional :meta, :message, 1, "v1.ListResponseMetadata"
      repeated :chunks, :message, 2, "v1.ReplayChunk"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.ReplayChunk" do
      optional :data, :bytes, 1
      repeated :events, :message, 2, "v1.ReplayChunkEvent"
      optional :symmetric_key, :string, 3
    end
    add_message "v1.ReplayChunkEvent" do
      optional :data, :bytes, 1
      optional :duration, :message, 2, "google.protobuf.Duration"
    end
  end
end

module V1
  ReplayListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ReplayListRequest").msgclass
  ReplayListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ReplayListResponse").msgclass
  ReplayChunk = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ReplayChunk").msgclass
  ReplayChunkEvent = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.ReplayChunkEvent").msgclass
end
