# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secret_store_healths.proto

require "google/protobuf"

require "google/protobuf/timestamp_pb"
require "options_pb"
require "spec_pb"
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("secret_store_healths.proto", :syntax => :proto3) do
    add_message "v1.SecretStoreHealthListRequest" do
      optional :meta, :message, 1, "v1.ListRequestMetadata"
      optional :filter, :string, 2
    end
    add_message "v1.SecretStoreHealthListResponse" do
      optional :meta, :message, 1, "v1.ListResponseMetadata"
      repeated :secret_store_healths, :message, 2, "v1.SecretStoreHealth"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.SecretStoreHealthCheckRequest" do
      optional :meta, :message, 1, "v1.CreateRequestMetadata"
      optional :secret_store_id, :string, 2
    end
    add_message "v1.SecretStoreHealthCheckResponse" do
      optional :meta, :message, 1, "v1.CreateResponseMetadata"
      optional :rate_limit, :message, 2, "v1.RateLimitMetadata"
    end
    add_message "v1.SecretStoreHealth" do
      optional :secret_store_id, :string, 1
      optional :node_id, :string, 2
      optional :detail, :string, 3
      optional :status, :string, 4
      optional :changed_at, :message, 6, "google.protobuf.Timestamp"
      optional :checked_at, :message, 7, "google.protobuf.Timestamp"
    end
  end
end

module V1
  SecretStoreHealthListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.SecretStoreHealthListRequest").msgclass
  SecretStoreHealthListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.SecretStoreHealthListResponse").msgclass
  SecretStoreHealthCheckRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.SecretStoreHealthCheckRequest").msgclass
  SecretStoreHealthCheckResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.SecretStoreHealthCheckResponse").msgclass
  SecretStoreHealth = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.SecretStoreHealth").msgclass
end
