# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workflows.proto

require "google/protobuf"

require "options_pb"
require "spec_pb"
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("workflows.proto", :syntax => :proto3) do
    add_message "v1.WorkflowListRequest" do
      optional :meta, :message, 1, "v1.ListRequestMetadata"
      optional :filter, :string, 2
    end
    add_message "v1.WorkflowListResponse" do
      optional :meta, :message, 1, "v1.ListResponseMetadata"
      repeated :workflows, :message, 2, "v1.Workflow"
    end
    add_message "v1.Workflow" do
      optional :id, :string, 1
      optional :name, :string, 2
      optional :description, :string, 3
      optional :weight, :int64, 4
      optional :auto_grant, :bool, 5
      optional :enabled, :bool, 6
      optional :requires_reason, :bool, 7
      optional :access_rules, :string, 8
    end
    add_message "v1.WorkflowRole" do
      optional :workflow_id, :string, 2
      optional :role_id, :string, 3
    end
    add_message "v1.WorkflowApprover" do
      optional :workflow_id, :string, 2
      optional :approver_id, :string, 3
    end
    add_message "v1.WorkflowAssignment" do
      optional :workflow_id, :string, 2
      optional :resource_id, :string, 3
    end
  end
end

module V1
  WorkflowListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.WorkflowListRequest").msgclass
  WorkflowListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.WorkflowListResponse").msgclass
  Workflow = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.Workflow").msgclass
  WorkflowRole = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.WorkflowRole").msgclass
  WorkflowApprover = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.WorkflowApprover").msgclass
  WorkflowAssignment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.WorkflowAssignment").msgclass
end
