# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: workflows.proto for package 'v1'

require "grpc"
require "workflows_pb"

module V1
  module Workflows
    # Workflows are the collection of rules that define the resources to which access can be requested,
    # the users that can request that access, and the mechanism for approving those requests which can either
    # but automatic approval or a set of users authorized to approve the requests.
    class Service
      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "v1.Workflows"

      # Lists existing workflows.
      rpc :List, V1::WorkflowListRequest, V1::WorkflowListResponse
    end

    Stub = Service.rpc_stub_class
  end
end
