# Copyright 2020 StrongDM Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: workflow_roles.proto

require "google/protobuf"

require "options_pb"
require "spec_pb"
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("workflow_roles.proto", :syntax => :proto3) do
    add_message "v1.WorkflowRolesCreateRequest" do
      optional :meta, :message, 1, "v1.CreateRequestMetadata"
      optional :workflow_role, :message, 2, "v1.WorkflowRole"
    end
    add_message "v1.WorkflowRolesCreateResponse" do
      optional :meta, :message, 1, "v1.CreateResponseMetadata"
      optional :workflow_role, :message, 2, "v1.WorkflowRole"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.WorkflowRoleGetRequest" do
      optional :meta, :message, 1, "v1.GetRequestMetadata"
      optional :id, :string, 2
    end
    add_message "v1.WorkflowRoleGetResponse" do
      optional :meta, :message, 1, "v1.GetResponseMetadata"
      optional :workflow_role, :message, 2, "v1.WorkflowRole"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.WorkflowRolesDeleteRequest" do
      optional :meta, :message, 1, "v1.DeleteRequestMetadata"
      optional :id, :string, 2
    end
    add_message "v1.WorkflowRolesDeleteResponse" do
      optional :meta, :message, 1, "v1.DeleteResponseMetadata"
      optional :rate_limit, :message, 2, "v1.RateLimitMetadata"
    end
    add_message "v1.WorkflowRolesListRequest" do
      optional :meta, :message, 1, "v1.ListRequestMetadata"
      optional :filter, :string, 2
    end
    add_message "v1.WorkflowRolesListResponse" do
      optional :meta, :message, 1, "v1.ListResponseMetadata"
      repeated :workflow_role, :message, 2, "v1.WorkflowRole"
      optional :rate_limit, :message, 3, "v1.RateLimitMetadata"
    end
    add_message "v1.WorkflowRole" do
      optional :id, :string, 1
      optional :workflow_id, :string, 2
      optional :role_id, :string, 3
    end
  end
end

module V1
  WorkflowRolesCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.WorkflowRolesCreateRequest").msgclass
  WorkflowRolesCreateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.WorkflowRolesCreateResponse").msgclass
  WorkflowRoleGetRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.WorkflowRoleGetRequest").msgclass
  WorkflowRoleGetResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.WorkflowRoleGetResponse").msgclass
  WorkflowRolesDeleteRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.WorkflowRolesDeleteRequest").msgclass
  WorkflowRolesDeleteResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.WorkflowRolesDeleteResponse").msgclass
  WorkflowRolesListRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.WorkflowRolesListRequest").msgclass
  WorkflowRolesListResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.WorkflowRolesListResponse").msgclass
  WorkflowRole = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("v1.WorkflowRole").msgclass
end
